// AUTO-GENERATED by scripts/gen-manifest.mjs — do not edit by hand.
// Run `node scripts/gen-manifest.mjs` (also runs on predev/prebuild).

import type { ModuleMeta } from './content';

export const generatedModules: ModuleMeta[] = [];
