// AUTO-GENERATED by scripts/gen-manifest.mjs — do not edit by hand.
// Run `node scripts/gen-manifest.mjs` (also runs on predev/prebuild).

import type { ModuleMeta } from './content';

export const generatedModules: ModuleMeta[] = [
	{
		"slug": "level-1-dasar/01-apa-itu-svelte",
		"title": "Apa itu Svelte & Filosofi Compiler",
		"level": 1,
		"levelTitle": "Dasar Svelte",
		"order": 1,
		"description": "Memahami Svelte sebagai compiler yang merakit kode update presisi saat build, bukan runtime ber-Virtual DOM seperti React/Vue.",
		"docs": "https://svelte.dev/docs/svelte/overview",
		"keywords": [
			"compiler",
			"virtual dom",
			"runtime",
			"reactivity",
			"svelte 5"
		],
		"updated": "2026-06-05T01:13:34+07:00"
	},
	{
		"slug": "level-1-dasar/02-setup-tooling",
		"title": "Setup & Tooling (npx sv create)",
		"level": 1,
		"levelTitle": "Dasar Svelte",
		"order": 2,
		"description": "Membuat proyek Svelte/SvelteKit dari nol dengan npx sv create, memahami struktur folder, dev server Vite, dan tooling editor.",
		"docs": "https://svelte.dev/docs/svelte/getting-started",
		"keywords": [
			"sv create",
			"sveltekit",
			"vite",
			"npm run dev",
			"struktur proyek",
			"tooling"
		],
		"updated": "2026-06-05T01:13:34+07:00"
	},
	{
		"slug": "level-1-dasar/03-anatomi-komponen",
		"title": "Anatomi Komponen .svelte & file .svelte.js/.ts",
		"level": 1,
		"levelTitle": "Dasar Svelte",
		"order": 3,
		"description": "Membedah tiga bagian sebuah komponen .svelte dan kapan logika reaktif dipindah ke file .svelte.js/.ts agar bisa dipakai bersama.",
		"docs": "https://svelte.dev/docs/svelte/svelte-files",
		"keywords": [
			"komponen",
			"svelte-files",
			"script-module",
			"svelte.js",
			"rune",
			"struktur"
		],
		"updated": "2026-06-05T01:13:34+07:00"
	},
	{
		"slug": "level-1-dasar/04-markup-dasar",
		"title": "Markup Dasar: Attributes & Text Expressions",
		"level": 1,
		"levelTitle": "Dasar Svelte",
		"order": 4,
		"description": "Cara menyisipkan nilai JS ke teks dan atribut HTML di Svelte, plus shorthand, spread, boolean attrs, dan komentar.",
		"docs": "https://svelte.dev/docs/svelte/basic-markup",
		"keywords": [
			"markup",
			"interpolation",
			"attributes",
			"shorthand",
			"spread props",
			"boolean attributes"
		],
		"updated": "2026-06-05T01:13:34+07:00"
	},
	{
		"slug": "level-1-dasar/05-styling",
		"title": "Styling: Scoped, Global, Custom Properties, Nested",
		"level": 1,
		"levelTitle": "Dasar Svelte",
		"order": 5,
		"description": "Memahami cara Svelte menata gaya komponen — scoped otomatis, :global(), CSS custom properties, serta directive class: dan style:.",
		"docs": "https://svelte.dev/docs/svelte/scoped-styles",
		"keywords": [
			"styling",
			"scoped",
			"global",
			"custom-properties",
			"class-directive",
			"style-directive"
		],
		"updated": "2026-06-05T01:13:34+07:00"
	},
	{
		"slug": "level-2-reactivity/01-apa-itu-runes",
		"title": "Apa itu Runes & Mengapa Ada",
		"level": 2,
		"levelTitle": "Reactivity (Runes)",
		"order": 1,
		"description": "Mengenal runes sebagai simbol $ yang menjadi instruksi compiler dan alasan ia menggantikan reaktivitas implisit Svelte 4.",
		"docs": "https://svelte.dev/docs/svelte/what-are-runes",
		"keywords": [
			"runes",
			"reactivity",
			"compiler",
			"$state",
			"svelte5"
		],
		"updated": "2026-06-05T01:13:34+07:00"
	},
	{
		"slug": "level-2-reactivity/02-state",
		"title": "$state, Deep State, $state.raw, $state.snapshot",
		"level": 2,
		"levelTitle": "Reactivity (Runes)",
		"order": 2,
		"description": "Memahami $state sebagai sumber kebenaran reaktif, deep reactivity lewat Proxy, serta varian $state.raw dan $state.snapshot.",
		"docs": "https://svelte.dev/docs/svelte/%24state",
		"keywords": [
			"state",
			"reactivity",
			"proxy",
			"deep-state",
			"snapshot",
			"runes"
		],
		"updated": "2026-06-05T01:13:34+07:00"
	},
	{
		"slug": "level-2-reactivity/03-derived",
		"title": "$derived & $derived.by",
		"level": 2,
		"levelTitle": "Reactivity (Runes)",
		"order": 3,
		"description": "Membuat nilai turunan yang menghitung ulang otomatis dengan $derived, dan menampung logika kompleks lewat $derived.by.",
		"docs": "https://svelte.dev/docs/svelte/%24derived",
		"keywords": [
			"derived",
			"derived.by",
			"computed",
			"reactivity",
			"runes",
			"svelte5"
		],
		"updated": "2026-06-05T01:13:34+07:00"
	},
	{
		"slug": "level-2-reactivity/04-effect",
		"title": "$effect, $effect.pre, $effect.root & Kapan TIDAK Pakai",
		"level": 2,
		"levelTitle": "Reactivity (Runes)",
		"order": 4,
		"description": "Memahami $effect untuk side effect reaktif beserta cleanup, varian $effect.pre & $effect.root, $effect.tracking, dan kapan justru tidak boleh memakai effect.",
		"docs": "https://svelte.dev/docs/svelte/%24effect",
		"keywords": [
			"$effect",
			"side-effect",
			"cleanup",
			"$effect.pre",
			"$effect.root",
			"$derived"
		],
		"updated": "2026-06-05T01:13:34+07:00"
	},
	{
		"slug": "level-2-reactivity/05-props-bindable",
		"title": "$props & $bindable",
		"level": 2,
		"levelTitle": "Reactivity (Runes)",
		"order": 5,
		"description": "Cara menerima props lewat $props() dengan destructuring, memberi tipe TS, dan membuka two-way binding secara opt-in dengan $bindable().",
		"docs": "https://svelte.dev/docs/svelte/%24props",
		"keywords": [
			"props",
			"$props",
			"$bindable",
			"two-way binding",
			"typescript",
			"rest props"
		],
		"updated": "2026-06-05T01:13:34+07:00"
	},
	{
		"slug": "level-2-reactivity/06-inspect-host",
		"title": "$inspect & $host",
		"level": 2,
		"levelTitle": "Reactivity (Runes)",
		"order": 6,
		"description": "Memakai $inspect untuk men-debug state reaktif (dev-only) dengan .with() dan .trace(), serta $host untuk mengakses elemen host pada custom element.",
		"docs": "https://svelte.dev/docs/svelte/%24inspect",
		"keywords": [
			"inspect",
			"host",
			"debug",
			"trace",
			"custom-element",
			"runes"
		],
		"updated": "2026-06-05T01:13:34+07:00"
	},
	{
		"slug": "level-3-template/01-control-flow",
		"title": "{#if}, {#each}, {#key}, {#await}",
		"level": 3,
		"levelTitle": "Template Syntax",
		"order": 1,
		"description": "Menguasai blok logika di markup Svelte — kondisi, perulangan, re-mount, dan menangani Promise langsung di template.",
		"docs": "https://svelte.dev/docs/svelte/if",
		"keywords": [
			"if",
			"each",
			"key",
			"await",
			"control-flow",
			"template"
		],
		"updated": "2026-06-05T01:13:34+07:00"
	},
	{
		"slug": "level-3-template/02-snippets",
		"title": "Snippets {#snippet} & {@render}",
		"level": 3,
		"levelTitle": "Template Syntax",
		"order": 2,
		"description": "Cara membuat potongan markup yang bisa dipakai ulang dengan {#snippet}, memanggilnya dengan {@render}, dan memakai snippet sebagai prop untuk menggantikan slot Svelte 4.",
		"docs": "https://svelte.dev/docs/svelte/snippet",
		"keywords": [
			"snippet",
			"render",
			"children",
			"slot",
			"render props",
			"scoped slot"
		],
		"updated": "2026-06-05T01:13:34+07:00"
	},
	{
		"slug": "level-3-template/03-tags",
		"title": "Tags: {@html}, {@const}, {@debug}, {@attach}",
		"level": 3,
		"levelTitle": "Template Syntax",
		"order": 3,
		"description": "Empat tag spesial Svelte untuk menyuntik HTML mentah, mendeklarasikan konstanta lokal di blok, mendebug nilai, dan menempelkan fungsi ke elemen DOM.",
		"docs": "https://svelte.dev/docs/svelte/@html",
		"keywords": [
			"html",
			"const",
			"debug",
			"attach",
			"attachment",
			"xss"
		],
		"updated": "2026-06-05T01:13:34+07:00"
	},
	{
		"slug": "level-3-template/04-directives",
		"title": "Directives: bind:, use:, style:, class",
		"level": 3,
		"levelTitle": "Template Syntax",
		"order": 4,
		"description": "Mengenal directive Svelte untuk two-way binding, actions, styling dinamis, dan kelas kondisional dengan sintaks modern Svelte 5.",
		"docs": "https://svelte.dev/docs/svelte/bind",
		"keywords": [
			"bind",
			"use",
			"action",
			"style",
			"class",
			"two-way binding"
		],
		"updated": "2026-06-05T01:13:34+07:00"
	},
	{
		"slug": "level-3-template/05-transitions",
		"title": "Transitions & Animations: transition:, in:/out:, animate:",
		"level": 3,
		"levelTitle": "Template Syntax",
		"order": 5,
		"description": "Membuat elemen masuk dan keluar dengan mulus lewat transition:, mengatur arah masuk/keluar terpisah, lalu menganimasikan list yang berubah urutan dengan animate: (FLIP).",
		"docs": "https://svelte.dev/docs/svelte/transition",
		"keywords": [
			"transition",
			"in",
			"out",
			"animate",
			"flip",
			"fade",
			"fly",
			"custom-transition"
		],
		"updated": "2026-06-05T01:13:34+07:00"
	},
	{
		"slug": "level-3-template/06-async-await",
		"title": "await Expressions (Async Svelte)",
		"level": 3,
		"levelTitle": "Template Syntax",
		"order": 6,
		"description": "Memakai await langsung di script, markup, dan $derived — plus $effect.pending dan <svelte:boundary> untuk loading state yang konsisten.",
		"docs": "https://svelte.dev/docs/svelte/await-expressions",
		"keywords": [
			"await",
			"async",
			"derived",
			"effect-pending",
			"boundary",
			"suspense"
		],
		"updated": "2026-06-05T01:13:34+07:00"
	},
	{
		"slug": "level-4-special-runtime/01-special-elements",
		"title": "Special Elements: <svelte:window/document/body/head/element/boundary/options>",
		"level": 4,
		"levelTitle": "Special Elements & Runtime",
		"order": 1,
		"description": "Mengenal elemen khusus <svelte:...> untuk menempel ke window/document/body/head, merender tag dinamis dengan <svelte:element>, menangkap error & loading dengan <svelte:boundary>, dan mengatur kompilasi lewat <svelte:options>.",
		"docs": "https://svelte.dev/docs/svelte/svelte-window",
		"keywords": [
			"svelte-window",
			"svelte-element",
			"svelte-boundary",
			"svelte-options",
			"special-elements"
		],
		"updated": "2026-06-05T01:13:34+07:00"
	},
	{
		"slug": "level-4-special-runtime/02-stores-vs-runes",
		"title": "Stores (writable/readable/derived/custom) vs Runes",
		"level": 4,
		"levelTitle": "Special Elements & Runtime",
		"order": 2,
		"description": "Memahami Svelte stores (writable, readable, derived, custom) dengan auto-subscribe $, lalu kapan memilih stores vs runes ($state di .svelte.ts) untuk state global.",
		"docs": "https://svelte.dev/docs/svelte/stores",
		"keywords": [
			"store",
			"writable",
			"readable",
			"derived",
			"custom store",
			"auto-subscribe",
			"runes",
			"state global"
		],
		"updated": "2026-06-05T01:13:34+07:00"
	},
	{
		"slug": "level-4-special-runtime/03-context-lifecycle",
		"title": "Context API, Lifecycle & Imperative Component API",
		"level": 4,
		"levelTitle": "Special Elements & Runtime",
		"order": 3,
		"description": "Cara berbagi data lintas kedalaman komponen lewat setContext/getContext, mengatur lifecycle dengan onMount/onDestroy/tick, dan mengontrol komponen secara imperatif lewat mount/unmount/render.",
		"docs": "https://svelte.dev/docs/svelte/context",
		"keywords": [
			"setContext",
			"getContext",
			"lifecycle",
			"onMount",
			"onDestroy",
			"mount",
			"tick"
		],
		"updated": "2026-06-05T01:13:34+07:00"
	},
	{
		"slug": "level-5-profesional/01-best-practices-ts",
		"title": "Best Practices & TypeScript di Svelte",
		"level": 5,
		"levelTitle": "Profesional",
		"order": 1,
		"description": "Memakai TypeScript penuh di Svelte 5 — mengetik $props lewat interface, generics komponen, typing $state/$derived, tipe Component, plus best practice struktur proyek.",
		"docs": "https://svelte.dev/docs/svelte/typescript",
		"keywords": [
			"typescript",
			"$props",
			"generics",
			"Component",
			"$state",
			"best-practices"
		],
		"updated": "2026-06-05T01:13:34+07:00"
	},
	{
		"slug": "level-5-profesional/02-testing",
		"title": "Testing: Vitest + Testing Library + Playwright",
		"level": 5,
		"levelTitle": "Profesional",
		"order": 2,
		"description": "Strategi testing Svelte 5 lengkap — unit logic .svelte.ts dengan flushSync & $effect.root, component test pakai @testing-library/svelte, dan E2E dengan Playwright, plus kapan memakai masing-masing.",
		"docs": "https://svelte.dev/docs/svelte/testing",
		"keywords": [
			"testing",
			"vitest",
			"testing-library",
			"playwright",
			"flushSync",
			"effect-root"
		],
		"updated": "2026-06-05T01:13:34+07:00"
	},
	{
		"slug": "level-5-profesional/03-custom-elements",
		"title": "Custom Elements / Web Components & Browser Support",
		"level": 5,
		"levelTitle": "Profesional",
		"order": 3,
		"description": "Mengkompilasi komponen Svelte 5 jadi Web Component standar dengan <svelte:options customElement>, $host(), props/events, shadow DOM, beserta batasan & dukungan browser-nya.",
		"docs": "https://svelte.dev/docs/svelte/custom-elements",
		"keywords": [
			"custom-elements",
			"web-components",
			"svelte:options",
			"$host",
			"shadow-dom"
		],
		"updated": "2026-06-05T01:13:34+07:00"
	},
	{
		"slug": "level-5-profesional/04-reference-modules",
		"title": "Reference Modules: motion, transition, easing, action, reactivity, events, store",
		"level": 5,
		"levelTitle": "Profesional",
		"order": 4,
		"description": "Mengenal modul bawaan Svelte 5 — Spring/Tween dari svelte/motion, transition & easing, tipe Action, koleksi reaktif SvelteMap/SvelteSet/SvelteDate, svelte/events, dan svelte/store.",
		"docs": "https://svelte.dev/docs/svelte/svelte-motion",
		"keywords": [
			"motion",
			"spring",
			"tween",
			"transition",
			"easing",
			"action",
			"reactivity",
			"store"
		],
		"updated": "2026-06-05T01:13:34+07:00"
	},
	{
		"slug": "level-5-profesional/05-migration",
		"title": "Migrasi Svelte 4 → 5 (+ Tabel Legacy vs Modern)",
		"level": 5,
		"levelTitle": "Profesional",
		"order": 5,
		"description": "Memetakan setiap API lama Svelte 4 ke padanan runes Svelte 5 — export let, $:, on:, slot, createEventDispatcher, svelte:component — plus strategi migrasi bertahap.",
		"docs": "https://svelte.dev/docs/svelte/v5-migration-guide",
		"keywords": [
			"migrasi",
			"runes",
			"legacy",
			"props",
			"snippet",
			"callback-prop"
		],
		"updated": "2026-06-05T01:13:34+07:00"
	},
	{
		"slug": "level-6-sveltekit-dasar/01-apa-itu-sveltekit",
		"title": "Apa itu SvelteKit & Beda dengan Svelte",
		"level": 6,
		"levelTitle": "SvelteKit Dasar",
		"order": 1,
		"description": "Memahami SvelteKit sebagai meta-framework full-stack di atas Svelte + Vite yang mengurus routing, SSR, dan build — peran setara Next.js (React) dan Nuxt (Vue).",
		"docs": "https://svelte.dev/docs/kit/introduction",
		"keywords": [
			"sveltekit",
			"meta-framework",
			"routing",
			"ssr",
			"vite",
			"project-structure"
		],
		"updated": "2026-06-05T01:13:34+07:00"
	},
	{
		"slug": "level-6-sveltekit-dasar/02-web-standards",
		"title": "Web Standards: Request/Response, fetch, FormData",
		"level": 6,
		"levelTitle": "SvelteKit Dasar",
		"order": 2,
		"description": "SvelteKit dibangun di atas API web standar (Request, Response, Headers, URL, FormData, fetch) sehingga kode-mu portable dan minim API framework-spesifik.",
		"docs": "https://svelte.dev/docs/kit/web-standards",
		"keywords": [
			"web-standards",
			"Request",
			"Response",
			"fetch",
			"FormData",
			"URL"
		],
		"updated": "2026-06-05T01:13:34+07:00"
	},
	{
		"slug": "level-6-sveltekit-dasar/03-routing",
		"title": "Routing: +page/+layout/+server",
		"level": 6,
		"levelTitle": "SvelteKit Dasar",
		"order": 3,
		"description": "Memahami file-based routing SvelteKit — bagaimana struktur folder src/routes memetakan URL ke halaman, layout, endpoint API, dan halaman error lewat file berawalan +.",
		"docs": "https://svelte.dev/docs/kit/routing",
		"keywords": [
			"routing",
			"+page",
			"+layout",
			"+server",
			"+error",
			"params",
			"file-based"
		],
		"updated": "2026-06-05T01:13:34+07:00"
	},
	{
		"slug": "level-6-sveltekit-dasar/04-loading-data",
		"title": "Loading Data: load, +page.js vs +page.server.js",
		"level": 6,
		"levelTitle": "SvelteKit Dasar",
		"order": 4,
		"description": "Memahami cara SvelteKit mengambil data halaman lewat fungsi load — perbedaan universal load (+page.js) dan server load (+page.server.js), layout load, invalidation, dan streaming.",
		"docs": "https://svelte.dev/docs/kit/load",
		"keywords": [
			"load",
			"page.js",
			"page.server.js",
			"layout-load",
			"invalidate",
			"streaming"
		],
		"updated": "2026-06-05T01:13:34+07:00"
	},
	{
		"slug": "level-6-sveltekit-dasar/05-form-actions",
		"title": "Form Actions + use:enhance",
		"level": 6,
		"levelTitle": "SvelteKit Dasar",
		"order": 5,
		"description": "Menulis mutasi data lewat HTML form di server (export const actions di +page.server.js), lalu meningkatkannya jadi mulus tanpa reload dengan use:enhance dan progressive enhancement.",
		"docs": "https://svelte.dev/docs/kit/form-actions",
		"keywords": [
			"form-actions",
			"use-enhance",
			"progressive-enhancement",
			"fail",
			"ActionData",
			"sveltekit"
		],
		"updated": "2026-06-05T01:13:34+07:00"
	},
	{
		"slug": "level-6-sveltekit-dasar/06-page-options",
		"title": "Page Options: SSR/CSR/prerender, trailingSlash",
		"level": 6,
		"levelTitle": "SvelteKit Dasar",
		"order": 6,
		"description": "Mengatur cara tiap halaman dirender — SSR, CSR, prerender (SSG), trailingSlash, dan config — lewat export konstanta di +page.js/+layout.js, baik per-route maupun global.",
		"docs": "https://svelte.dev/docs/kit/page-options",
		"keywords": [
			"page-options",
			"ssr",
			"csr",
			"prerender",
			"ssg",
			"trailingslash"
		],
		"updated": "2026-06-05T01:13:34+07:00"
	},
	{
		"slug": "level-6-sveltekit-dasar/07-state-remote",
		"title": "State Management di SSR & Remote Functions",
		"level": 6,
		"levelTitle": "SvelteKit Dasar",
		"order": 7,
		"description": "Cara mengelola state dengan aman di lingkungan SSR SvelteKit dan mengambil data lewat remote functions (query/form/command) yang type-safe.",
		"docs": "https://svelte.dev/docs/kit/state-management",
		"keywords": [
			"state-management",
			"ssr",
			"remote-functions",
			"context",
			"query",
			"command"
		],
		"updated": "2026-06-05T01:13:34+07:00"
	},
	{
		"slug": "level-7-sveltekit-lanjutan/01-advanced-routing",
		"title": "Advanced Routing: rest/optional params, matchers, groups",
		"level": 7,
		"levelTitle": "SvelteKit Lanjutan",
		"order": 1,
		"description": "Menguasai bentuk-bentuk lanjutan file-based routing SvelteKit — rest params, optional params, param matchers, route groups, layout breaking, dan encoding karakter spesial.",
		"docs": "https://svelte.dev/docs/kit/advanced-routing",
		"keywords": [
			"advanced routing",
			"rest params",
			"optional params",
			"matchers",
			"route groups",
			"layout breaking"
		],
		"updated": "2026-06-05T01:13:34+07:00"
	},
	{
		"slug": "level-7-sveltekit-lanjutan/02-hooks",
		"title": "Hooks: handle, handleFetch, handleError, reroute",
		"level": 7,
		"levelTitle": "SvelteKit Lanjutan",
		"order": 2,
		"description": "Menulis kode yang berjalan untuk SETIAP request/navigasi lewat hooks SvelteKit — handle, handleFetch, handleError di server, plus reroute & transport universal, lalu menggabungkannya dengan sequence().",
		"docs": "https://svelte.dev/docs/kit/hooks",
		"keywords": [
			"hooks",
			"handle",
			"handleFetch",
			"handleError",
			"reroute",
			"transport",
			"sequence",
			"locals"
		],
		"updated": "2026-06-05T01:13:34+07:00"
	},
	{
		"slug": "level-7-sveltekit-lanjutan/03-errors-links-sw",
		"title": "Error Handling, Link Options, Service Workers",
		"level": 7,
		"levelTitle": "SvelteKit Lanjutan",
		"order": 3,
		"description": "Membedakan expected vs unexpected errors dengan error()/+error.svelte, mengatur preload & reload lewat link options, dan memakai service worker bawaan SvelteKit via $service-worker.",
		"docs": "https://svelte.dev/docs/kit/errors",
		"keywords": [
			"errors",
			"error-boundary",
			"link-options",
			"preload",
			"service-worker",
			"pwa"
		],
		"updated": "2026-06-05T01:13:34+07:00"
	},
	{
		"slug": "level-7-sveltekit-lanjutan/04-server-only-advanced",
		"title": "Server-only Modules, Snapshots, Shallow Routing, Observability, Packaging",
		"level": 7,
		"levelTitle": "SvelteKit Lanjutan",
		"order": 4,
		"description": "Mengamankan kode rahasia di server, menyimpan state UI lewat snapshots, navigasi dangkal dengan shallow routing, observability/tracing, dan mem-package library dengan svelte-package.",
		"docs": "https://svelte.dev/docs/kit/server-only-modules",
		"keywords": [
			"server-only",
			"snapshots",
			"shallow-routing",
			"observability",
			"packaging",
			"svelte-package"
		],
		"updated": "2026-06-05T01:13:34+07:00"
	},
	{
		"slug": "level-8-expert/01-building-adapters",
		"title": "Building & Adapters (auto/node/static/Cloudflare/Netlify/Vercel/SPA)",
		"level": 8,
		"levelTitle": "Expert",
		"order": 1,
		"description": "Memahami cara `vite build` membungkus aplikasi SvelteKit dan bagaimana adapter (auto, node, static, Cloudflare, Netlify, Vercel, SPA) mengubah output itu agar pas dengan platform tujuan.",
		"docs": "https://svelte.dev/docs/kit/adapters",
		"keywords": [
			"adapters",
			"build",
			"adapter-node",
			"adapter-static",
			"ssg",
			"spa",
			"deployment"
		],
		"updated": "2026-06-05T01:13:34+07:00"
	},
	{
		"slug": "level-8-expert/02-env-vars",
		"title": "Environment Variables ($env/static, $env/dynamic, public vs private)",
		"level": 8,
		"levelTitle": "Expert",
		"order": 2,
		"description": "Memahami empat modul environment SvelteKit ($env/static & $env/dynamic, masing-masing public & private), kapan memakai yang mana, dan cara menjaga secret tidak bocor ke browser lewat prefix PUBLIC_.",
		"docs": "https://svelte.dev/docs/kit/$env-static-private",
		"keywords": [
			"env",
			"environment variables",
			"static",
			"dynamic",
			"public",
			"private",
			"PUBLIC_",
			"secret"
		],
		"updated": "2026-06-05T01:13:34+07:00"
	},
	{
		"slug": "level-8-expert/03-app-modules",
		"title": "$app/* Modules (state, navigation, forms, paths, server, stores)",
		"level": 8,
		"levelTitle": "Expert",
		"order": 3,
		"description": "Mengenal modul bawaan SvelteKit `$app/*` — `$app/state` (page/navigating/updated), `$app/navigation` (goto/invalidate/preloadData), `$app/forms` (enhance/applyAction), `$app/paths`, dan `$app/server` — beserta kapan dan kenapa memakainya.",
		"docs": "https://svelte.dev/docs/kit/$app-state",
		"keywords": [
			"app-state",
			"app-navigation",
			"app-forms",
			"enhance",
			"goto",
			"invalidate",
			"app-paths"
		],
		"updated": "2026-06-05T01:13:34+07:00"
	},
	{
		"slug": "level-8-expert/04-api-routes",
		"title": "API Routes +server.js (vs Nest.js, Express, Next route handlers)",
		"level": 8,
		"levelTitle": "Expert",
		"order": 4,
		"description": "Membuat endpoint HTTP murni di SvelteKit lewat `+server.js` (GET/POST/PUT/PATCH/DELETE) dengan `RequestHandler` dan helper `json()`, lalu memutuskan kapan cukup SvelteKit saja vs perlu backend terpisah seperti Nest.js.",
		"docs": "https://svelte.dev/docs/kit/routing",
		"keywords": [
			"+server.js",
			"RequestHandler",
			"json",
			"content-negotiation",
			"REST",
			"api-routes",
			"nestjs"
		],
		"updated": "2026-06-05T01:13:34+07:00"
	},
	{
		"slug": "level-8-expert/05-auth-perf-seo",
		"title": "Auth, Performance, Images, SEO, Accessibility, Icons",
		"level": 8,
		"levelTitle": "Expert",
		"order": 5,
		"description": "Membangun lapisan produksi sebuah aplikasi SvelteKit — autentikasi berbasis cookie/session lewat hooks & locals, optimasi performa (preload & code-split), gambar dengan enhanced-img, SEO yang benar lewat SSR, aksesibilitas, dan strategi icon.",
		"docs": "https://svelte.dev/docs/kit/auth",
		"keywords": [
			"auth",
			"session",
			"hooks",
			"locals",
			"performance",
			"enhanced-img",
			"seo",
			"a11y"
		],
		"updated": "2026-06-05T01:13:34+07:00"
	},
	{
		"slug": "level-8-expert/06-studi-kasus",
		"title": "Studi Kasus Akhir: Aplikasi Lengkap (Blog/Dashboard) End-to-End",
		"level": 8,
		"levelTitle": "Expert",
		"order": 6,
		"description": "Merangkai seluruh fitur SvelteKit jadi satu aplikasi nyata — routing, layout, server load, form actions, auth via hooks/locals, endpoint API, sampai adapter & deploy.",
		"docs": "https://svelte.dev/docs/kit/introduction",
		"keywords": [
			"studi kasus",
			"sveltekit",
			"arsitektur",
			"hooks",
			"form actions",
			"end-to-end"
		],
		"updated": "2026-06-05T01:13:34+07:00"
	}
];
