// scripts/gen-data.mjs — emits src/lib/pages.generated.ts from pages.data.mjs.
// Provides the app's "expected coverage" list (for /kelengkapan) + old→new
// redirect map. Run on predev/prebuild (see package.json).
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';
import { PAGES, slugOf } from './pages.data.mjs';

const root = fileURLToPath(new URL('..', import.meta.url));
const out = join(root, 'src/lib/pages.generated.ts');

const official = PAGES.map((p) => ({
	slug: slugOf(p),
	product: p.product,
	section: p.section,
	sectionTitle: p.sectionTitle,
	sectionOrder: p.sectionOrder,
	order: p.order,
	title: p.title,
	status: p.status,
	docs: p.docs
}));

// old slug -> new slug (first page that names it as `seed` wins)
const redirects = {};
for (const p of PAGES) {
	if (p.seed && !(p.seed in redirects)) redirects[p.seed] = slugOf(p);
}

const banner = `// AUTO-GENERATED by scripts/gen-data.mjs — do not edit by hand.\n`;
const body =
	`import type { Product, Status } from './content';\n\n` +
	`export type OfficialPage = {\n\tslug: string; product: Product; section: string;\n` +
	`\tsectionTitle: string; sectionOrder: number; order: number;\n\ttitle: string; status: Status; docs: string;\n};\n\n` +
	`export const officialPages: OfficialPage[] = ${JSON.stringify(official, null, '\t')};\n\n` +
	`export const redirects: Record<string, string> = ${JSON.stringify(redirects, null, '\t')};\n`;

writeFileSync(out, banner + '\n' + body);
console.log(
	`[gen-data] ${official.length} pages, ${Object.keys(redirects).length} redirects → ${join('src/lib', 'pages.generated.ts')}`
);
