// scripts/pages.data.mjs
// SINGLE SOURCE OF TRUTH for every official docs page we mirror.
// Consumed by: scripts/gen-data.mjs (app data + redirects),
//              scripts/gen-briefs.mjs (authoring workflow briefs).
//
// Verified against live docs on 2026-06-06 (svelte.dev). Deltas vs the original
// spec §G that were folded in here:
//   - SvelteKit › Core concepts: + "Environment variables" (v2.62+).
//   - SvelteKit › Reference: + $app/env, $app/env/private, $app/env/public.
//   - CLI: full set (Introduction, Commands, Add-ons ×13, API ×2) = 21 pages,
//     per the prompt's request to include the CLI add-ons & community guide.
// Totals: Svelte 86 · SvelteKit 71 · CLI 21 = 178.
//
// Entry shape (built by sec()): product, section, sectionTitle, sectionOrder,
//   page, order, title, status, docs, seed, analogy, compare, cover, playground.

const BASE = {
	svelte: 'https://svelte.dev/docs/svelte/',
	kit: 'https://svelte.dev/docs/kit/',
	cli: 'https://svelte.dev/docs/cli/'
};

/** Build the app slug + content path from an entry. CLI pages are flat. */
export function slugOf(p) {
	return p.product === 'cli' ? `cli/${p.page}` : `${p.product}/${p.section}/${p.page}`;
}

/** Build a section's entries. `rows` carry page/title/docsSlug + optional extras. */
function sec(product, section, sectionTitle, sectionOrder, rows) {
	return rows.map((r, i) => ({
		product,
		section,
		sectionTitle,
		sectionOrder,
		order: i + 1,
		page: r.page,
		title: r.title,
		status: r.status ?? 'stable',
		docs: BASE[product] + r.d,
		seed: r.seed ?? null,
		analogy: r.analogy ?? null,
		compare: r.compare ?? null,
		cover: r.cover,
		playground: r.pg ?? false
	}));
}

const cmp = (task, fw, note) => ({ task, fw, note });

// =====================================================================
// SVELTE (86)
// =====================================================================
const SVELTE = [
	...sec('svelte', 'introduction', 'Introduction', 1, [
		{ page: 'overview', title: 'Overview', d: 'overview', seed: 'level-1-dasar/01-apa-itu-svelte',
		  analogy: 'compiler = tukang yang merakit furniture di pabrik, bukan di rumahmu; yang dikirim sudah jadi & ringan.',
		  compare: cmp('Model eksekusi: compiler vs Virtual DOM', ['react', 'vue'], 'React/Vue diff VDOM saat runtime; Svelte meng-compile update presisi saat build.'),
		  cover: 'Svelte sebagai compiler (bukan runtime/VDOM); "write less code"; output JS ringan; posisi Svelte vs SvelteKit.' },
		{ page: 'getting-started', title: 'Getting started', d: 'getting-started', seed: 'level-1-dasar/02-setup-tooling',
		  cover: 'npx sv create; memilih template; struktur proyek; npm run dev; Vite; ekstensi editor; alternatif (Vite plugin, REPL).' },
		{ page: 'svelte-files', title: '.svelte files', d: 'svelte-files', seed: 'level-1-dasar/03-anatomi-komponen', pg: true,
		  compare: cmp('Struktur satu komponen', ['react', 'vue'], 'React: 1 fungsi+JSX; Vue SFC: 3 blok; Svelte: mirip SFC tapi reaktivitas dari compiler.'),
		  cover: 'Bagian <script>, <script module>, markup, <style> dalam .svelte; urutan eksekusi; aturan dasar.' },
		{ page: 'svelte-js-files', title: '.svelte.js & .svelte.ts files', d: 'svelte-js-files', seed: 'level-1-dasar/03-anatomi-komponen',
		  cover: 'File .svelte.js/.svelte.ts untuk logika reaktif (runes) yang bisa di-share antar komponen; kapan dipakai; batasannya.' }
	]),
	...sec('svelte', 'runes', 'Runes', 2, [
		{ page: 'what-are-runes', title: 'What are runes?', d: 'what-are-runes', seed: 'level-2-reactivity/01-apa-itu-runes', pg: true,
		  analogy: 'runes = "mantra" $ yang memberi tahu compiler bagian mana yang hidup/reaktif.',
		  cover: 'Runes = simbol $ sebagai instruksi compiler; mengapa menggantikan reaktivitas implisit Svelte 4 ($:); di mana boleh dipakai.' },
		{ page: 'state', title: '$state', d: '$state', seed: 'level-2-reactivity/02-state', pg: true,
		  analogy: 'papan tulis ajaib: ubah satu angka, semua hitungan yang bergantung ikut berubah.',
		  compare: cmp('State reaktif lokal', ['react', 'vue'], 'useState butuh setter & immutable update; Vue ref butuh .value; $state bisa dimutasi langsung.'),
		  cover: '$state dasar; deep reactivity via Proxy untuk object/array; $state.raw (non-deep); $state.snapshot; class fields.' },
		{ page: 'derived', title: '$derived', d: '$derived', seed: 'level-2-reactivity/03-derived', pg: true,
		  analogy: 'nilai turunan papan tulis ajaib yang dihitung ulang otomatis.',
		  compare: cmp('Nilai terkomputasi', ['react', 'vue'], 'useMemo butuh dependency array; Vue computed mirip; $derived melacak dependency otomatis.'),
		  cover: '$derived(expr); $derived.by(()=>{}); bebas efek samping; dependency otomatis; override sementara; destructuring.' },
		{ page: 'effect', title: '$effect', d: '$effect', seed: 'level-2-reactivity/04-effect', pg: true,
		  analogy: 'asisten yang selalu mengintip perubahan lalu bereaksi (nyalakan lampu tiap pintu dibuka).',
		  compare: cmp('Side effect reaktif', ['react', 'vue'], 'useEffect butuh dependency array & sering jadi sumber bug; $effect melacak otomatis; Vue watchEffect mirip.'),
		  cover: '$effect (setelah DOM) + cleanup; $effect.pre; $effect.root; $effect.tracking; KAPAN TIDAK pakai effect (pakai $derived).' },
		{ page: 'props', title: '$props', d: '$props', seed: 'level-2-reactivity/05-props-bindable', pg: true,
		  compare: cmp('Menerima props', ['react', 'vue'], 'React props lewat argumen fungsi; Vue defineProps; Svelte let { a, b = d, ...rest } = $props().'),
		  cover: 'let { a, b = default, ...rest } = $props(); rename; tipe props (TS interface); $props.id(); fallback values.' },
		{ page: 'bindable', title: '$bindable', d: '$bindable', seed: 'level-2-reactivity/05-props-bindable', pg: true,
		  compare: cmp('Two-way binding prop', ['react', 'vue'], 'React one-way + callback; Vue v-model/defineModel; Svelte $bindable() opt-in di child.'),
		  cover: 'let { value = $bindable() } = $props(); two-way binding antar komponen; default; kapan layak two-way.' },
		{ page: 'inspect', title: '$inspect', d: '$inspect', seed: 'level-2-reactivity/06-inspect-host', pg: true,
		  cover: '$inspect(...) debug dev-only (log saat berubah); $inspect(...).with(fn); $inspect.trace() (5.14+); hilang di build produksi.' },
		{ page: 'host', title: '$host', d: '$host', seed: 'level-2-reactivity/06-inspect-host',
		  cover: '$host() untuk mengakses elemen host saat komponen di-compile sebagai custom element; dispatch CustomEvent; hanya untuk customElement.' }
	]),
	...sec('svelte', 'template', 'Template syntax', 3, [
		{ page: 'basic-markup', title: 'Basic markup', d: 'basic-markup', seed: 'level-1-dasar/04-markup-dasar', pg: true,
		  compare: cmp('Interpolasi & atribut', ['react', 'vue'], 'JSX className vs HTML class; Svelte pakai HTML asli + {expr} & shorthand {value}.'),
		  cover: 'Text interpolation {expr}; attribute & shorthand {value}; spread props; boolean attrs; komentar; beda dari JSX.' },
		{ page: 'if', title: '{#if ...}', d: 'if', seed: 'level-3-template/01-control-flow', pg: true,
		  compare: cmp('Rendering kondisional', ['react', 'vue'], 'JSX pakai && / ternary; Vue v-if/v-else; Svelte blok {#if}/{:else if}/{:else}.'),
		  cover: '{#if}/{:else if}/{:else}; ekspresi kondisi; nesting; beda dengan v-if (tidak ada di markup mentah).' },
		{ page: 'each', title: '{#each ...}', d: 'each', seed: 'level-3-template/01-control-flow', pg: true,
		  compare: cmp('List rendering', ['react', 'vue'], 'JSX .map()+key; Vue v-for :key; Svelte {#each list as item, i (key)} keyed eksplisit.'),
		  cover: '{#each list as item, i (key)}; keyed vs unkeyed; destructuring; {:else} kosong; each atas Map/Set; index.' },
		{ page: 'key', title: '{#key ...}', d: 'key', seed: 'level-3-template/01-control-flow', pg: true,
		  cover: '{#key expr} untuk me-remount konten saat nilai berubah; memicu transition; kapan dibutuhkan.' },
		{ page: 'await', title: '{#await ...}', d: 'await', seed: 'level-3-template/01-control-flow', pg: true,
		  compare: cmp('Render promise', ['react', 'vue'], 'React butuh Suspense/state; Vue <Suspense>; Svelte {#await}/{:then}/{:catch} bawaan.'),
		  cover: '{#await promise}/{:then value}/{:catch err}; bentuk singkat; pending state; reaktif saat promise berganti.' },
		{ page: 'snippet', title: '{#snippet ...}', d: 'snippet', seed: 'level-3-template/02-snippets', pg: true,
		  compare: cmp('Konten yang bisa disisipkan', ['react', 'vue'], 'React children/render props; Vue slots; Svelte snippets eksplisit & berargumen — pengganti <slot>.'),
		  cover: '{#snippet name(args)}…{/snippet}; snippet sebagai prop; children implisit; reuse markup berulang.' },
		{ page: 'render', title: '{@render ...}', d: '@render', seed: 'level-3-template/02-snippets', pg: true,
		  cover: '{@render snippet(args)}; {@render children?.()} opsional; merender snippet/children; pasangan dari {#snippet}.' },
		{ page: 'html', title: '{@html ...}', d: '@html', seed: 'level-3-template/03-tags', pg: true,
		  cover: '{@html string} untuk menyisipkan HTML mentah; risiko XSS & cara sanitasi; styling konten @html (:global).' },
		{ page: 'attach', title: '{@attach ...}', d: '@attach', seed: 'level-3-template/03-tags', pg: true,
		  analogy: 'attachment = stiker fungsi yang menempel ke elemen saat ia muncul di DOM.',
		  cover: '{@attach fn} attachment modern (pengganti action use:); jalankan saat mount + cleanup; reaktif; factory.' },
		{ page: 'const', title: '{@const ...}', d: '@const', seed: 'level-3-template/03-tags', pg: true,
		  cover: '{@const x = ...} mendefinisikan konstanta lokal di dalam blok ({#each}/{#if}/snippet); batasan penempatan.' },
		{ page: 'debug', title: '{@debug ...}', d: '@debug', seed: 'level-3-template/03-tags', pg: true,
		  cover: '{@debug var1, var2} log + breakpoint debugger saat nilai berubah; {@debug} tanpa argumen; dev-only.' },
		{ page: 'declaration-tags', title: '{@const} / declaration tags', d: 'declaration-tags', seed: 'level-3-template/03-tags',
		  cover: 'Ringkas tag deklarasi let/const dalam template dan aturannya; rujuk {@const}.' },
		{ page: 'bind', title: 'bind:', d: 'bind', seed: 'level-3-template/04-directives', pg: true,
		  compare: cmp('Two-way binding input', ['react', 'vue'], 'React controlled (value+onChange); Vue v-model; Svelte bind:value & teman-temannya.'),
		  cover: 'bind:value/checked/group/files/this; bind:property komponen; bind dimensi (clientWidth); function bindings (get/set).' },
		{ page: 'use', title: 'use:', d: 'use', seed: 'level-3-template/04-directives', pg: true,
		  cover: 'use:action; Action type (param + update + destroy); kapan pakai action vs {@attach}; contoh tooltip/clickOutside.' },
		{ page: 'transition', title: 'transition:', d: 'transition', seed: 'level-3-template/05-transitions', pg: true,
		  compare: cmp('Animasi masuk/keluar', ['vue', 'react'], 'Vue <Transition>; React butuh library (Framer Motion); Svelte transition: bawaan.'),
		  cover: 'transition:fn (fade/fly/slide/scale); parameter; |local vs |global; events introstart/outroend; custom transition (css/tick).' },
		{ page: 'in-and-out', title: 'in: and out:', d: 'in-and-out', seed: 'level-3-template/05-transitions', pg: true,
		  cover: 'in:/out: untuk transition masuk & keluar berbeda (tidak dibalik seperti transition:); kombinasi.' },
		{ page: 'animate', title: 'animate:', d: 'animate', seed: 'level-3-template/05-transitions', pg: true,
		  cover: 'animate:flip untuk reorder list ber-key (FLIP); parameter (duration/easing); syarat keyed {#each}; custom animate.' },
		{ page: 'style', title: 'style:', d: 'style', seed: 'level-3-template/04-directives', pg: true,
		  cover: 'style:prop={value}; style:prop|important; banyak style: vs atribut style; reaktivitas; kombinasi dengan class.' },
		{ page: 'class', title: 'class', d: 'class', seed: 'level-3-template/04-directives', pg: true,
		  cover: 'Atribut class dengan objek/array (Svelte 5, via clsx); class:name lama; kapan masing-masing; menggabungkan kelas dinamis.' },
		{ page: 'await-expressions', title: 'await (expressions)', d: 'await-expressions', seed: 'level-3-template/06-async-await',
		  cover: 'await langsung di <script>/markup/$derived (async Svelte terbaru); {#await} vs await expression; $effect.pending; <svelte:boundary> loading.' }
	]),
	...sec('svelte', 'styling', 'Styling', 4, [
		{ page: 'scoped-styles', title: 'Scoped styles', d: 'scoped-styles', seed: 'level-1-dasar/05-styling', pg: true,
		  compare: cmp('Scoped styling', ['vue', 'react'], 'Vue <style scoped>; React butuh CSS Modules/CSS-in-JS; Svelte scoped by default (hash atribut).'),
		  cover: 'Scope otomatis lewat hash; spesifisitas; bagaimana selector di-scope; keyframes scoped.' },
		{ page: 'global-styles', title: 'Global styles', d: 'global-styles', seed: 'level-1-dasar/05-styling', pg: true,
		  cover: ':global(selector); blok :global {}; kapan butuh global; styling konten {@html}; global keyframes.' },
		{ page: 'custom-properties', title: 'Custom properties', d: 'custom-properties', seed: 'level-1-dasar/05-styling', pg: true,
		  cover: 'Mengoper CSS custom properties ke komponen (--bg={value}); membaca var(--x); tema via custom props.' },
		{ page: 'nested-style-elements', title: 'Nested <style> elements', d: 'nested-style-elements', seed: 'level-1-dasar/05-styling',
		  cover: 'Aturan untuk <style> bertingkat/dalam markup; hanya satu <style> top-level yang di-scope; sisanya literal.' }
	]),
	...sec('svelte', 'special-elements', 'Special elements', 5, [
		{ page: 'boundary', title: '<svelte:boundary>', d: 'svelte-boundary', seed: 'level-4-special-runtime/01-special-elements', pg: true,
		  analogy: 'jaring pengaman: kalau bagian dalam jatuh (error), jaring menangkap & menampilkan cadangan.',
		  cover: '<svelte:boundary onerror failed={snippet}>; menangkap error render; pending; reset; batasan (tidak menangkap event handler).' },
		{ page: 'window', title: '<svelte:window>', d: 'svelte-window', seed: 'level-4-special-runtime/01-special-elements', pg: true,
		  cover: '<svelte:window bind:scrollY bind:innerWidth on...>; listener window deklaratif; auto-cleanup.' },
		{ page: 'document', title: '<svelte:document>', d: 'svelte-document', seed: 'level-4-special-runtime/01-special-elements', pg: true,
		  cover: '<svelte:document> untuk event/bind pada document (visibilitychange, selectionchange, dll).' },
		{ page: 'body', title: '<svelte:body>', d: 'svelte-body', seed: 'level-4-special-runtime/01-special-elements', pg: true,
		  cover: '<svelte:body on:mouseenter…> untuk listener pada <body>; kegunaan umum.' },
		{ page: 'head', title: '<svelte:head>', d: 'svelte-head', seed: 'level-4-special-runtime/01-special-elements', pg: true,
		  cover: '<svelte:head> menyisipkan ke <head> (title, meta, link); SSR-friendly; interaksi dengan SvelteKit.' },
		{ page: 'element', title: '<svelte:element>', d: 'svelte-element', seed: 'level-4-special-runtime/01-special-elements', pg: true,
		  cover: '<svelte:element this={tag}> merender tag dinamis; this null; atribut & event dinamis.' },
		{ page: 'options', title: '<svelte:options>', d: 'svelte-options', seed: 'level-4-special-runtime/01-special-elements',
		  cover: '<svelte:options runes customElement namespace css...> opsi compiler per-komponen; runes mode; immutable (legacy).' }
	]),
	...sec('svelte', 'runtime', 'Runtime', 6, [
		{ page: 'stores', title: 'Stores', d: 'stores', seed: 'level-4-special-runtime/02-stores-vs-runes', pg: true,
		  compare: cmp('State global', ['react', 'vue'], 'Redux/Zustand (React), Pinia (Vue); di Svelte 5 sering cukup runes di .svelte.ts atau stores untuk pola RxJS-like.'),
		  cover: 'writable/readable/derived; auto-subscribe $store; custom store; KAPAN pakai store vs runes ($state di .svelte.ts).' },
		{ page: 'context', title: 'Context', d: 'context', seed: 'level-4-special-runtime/03-context-lifecycle', pg: true,
		  analogy: 'context = titip pesan lewat keluarga, tak perlu oper tangan ke tangan (lawan prop drilling).',
		  compare: cmp('Berbagi data lintas kedalaman', ['react', 'vue'], 'React Context.Provider/useContext; Vue provide/inject; Svelte setContext/getContext (per-tree, bukan reaktif sendiri).'),
		  cover: 'setContext/getContext/hasContext/getAllContexts; menyimpan state reaktif di context; pola provider; batasan timing.' },
		{ page: 'lifecycle-hooks', title: 'Lifecycle hooks', d: 'lifecycle-hooks', seed: 'level-4-special-runtime/03-context-lifecycle', pg: true,
		  compare: cmp('Lifecycle', ['react', 'vue'], 'React useEffect mount/cleanup; Vue onMounted/onUnmounted; Svelte onMount/onDestroy + tick (banyak hal kini cukup $effect).'),
		  cover: 'onMount (+ return cleanup), onDestroy, tick; mengapa beforeUpdate/afterUpdate deprecated (pakai $effect.pre/$effect).' },
		{ page: 'imperative-component-api', title: 'Imperative component API', d: 'imperative-component-api', seed: 'level-4-special-runtime/03-context-lifecycle',
		  cover: 'mount/unmount/render/hydrate dari "svelte"; membuat komponen secara imperatif; props reaktif via $state; flushSync.' },
		{ page: 'hydratable', title: 'Hydratable data', d: 'hydratable', seed: 'level-4-special-runtime/03-context-lifecycle',
		  cover: 'API hydratable untuk membagikan data antara render server & hidrasi klien tanpa fetch ulang; kapan relevan.' }
	]),
	...sec('svelte', 'misc', 'Misc', 7, [
		{ page: 'best-practices', title: 'Best practices', d: 'best-practices', seed: 'level-5-profesional/01-best-practices-ts',
		  cover: 'Pola idiomatik Svelte 5: $derived vs $effect, struktur komponen, aksesibilitas, performa, hindari anti-pattern reaktivitas.' },
		{ page: 'testing', title: 'Testing', d: 'testing', seed: 'level-5-profesional/02-testing',
		  cover: 'Vitest unit (logika .svelte.ts, flushSync, $effect.root); @testing-library/svelte; Playwright E2E; kapan pakai yang mana.' },
		{ page: 'typescript', title: 'TypeScript', d: 'typescript', seed: 'level-5-profesional/01-best-practices-ts', pg: true,
		  cover: 'lang="ts"; mengetik $props (interface), generics komponen (generics attr), $state/$derived; Component & Snippet types; konfigurasi.' },
		{ page: 'custom-elements', title: 'Custom elements', d: 'custom-elements', seed: 'level-5-profesional/03-custom-elements',
		  cover: '<svelte:options customElement="nama">; $host(); props/events; shadow DOM; batasan; mendaftarkan & memakai di luar Svelte.' },
		{ page: 'browser-support', title: 'Browser support', d: 'browser-support', seed: 'level-5-profesional/03-custom-elements',
		  cover: 'Target browser yang didukung Svelte 5; fitur JS yang diasumsikan; polyfill; pertimbangan legacy.' },
		{ page: 'v4-migration-guide', title: 'Svelte 4 migration guide', d: 'v4-migration-guide', seed: 'level-5-profesional/05-migration',
		  cover: 'Migrasi Svelte 3 → 4: perubahan minor, tooling, tipe; ringkas (fokus kompatibilitas).' },
		{ page: 'v5-migration-guide', title: 'Svelte 5 migration guide', d: 'v5-migration-guide', seed: 'level-5-profesional/05-migration',
		  cover: 'export let→$props; $:→$derived/$effect; on:→onX; <slot>→snippet; createEventDispatcher→callback; svelte:component; tabel legacy↔modern (<LegacyVsModern>).' },
		{ page: 'faq', title: 'Frequently asked questions', d: 'faq', seed: 'level-5-profesional/01-best-practices-ts',
		  cover: 'Pertanyaan umum Svelte: dukungan, perbandingan, format kode, routing (→SvelteKit), dsb. Tabel tanya-jawab ringkas.' }
	]),
	...sec('svelte', 'reference', 'Reference', 8, [
		{ page: 'svelte', title: 'svelte', d: 'svelte', status: 'reference', seed: 'level-5-profesional/04-reference-modules',
		  cover: 'Export inti modul "svelte": mount, unmount, hydrate, render, tick, untrack, getContext/setContext, createRawSnippet, tipe (Component, Snippet, ...).' },
		{ page: 'svelte-action', title: 'svelte/action', d: 'svelte-action', status: 'reference', seed: 'level-5-profesional/04-reference-modules', pg: true,
		  cover: 'Tipe Action & ActionReturn (update/destroy); Attachment; cara mengetik parameter action; contoh.' },
		{ page: 'svelte-animate', title: 'svelte/animate', d: 'svelte-animate', status: 'reference', seed: 'level-5-profesional/04-reference-modules', pg: true,
		  cover: 'flip(node, from, to, params) untuk animate:; parameter (delay/duration/easing); contoh reorder.' },
		{ page: 'svelte-attachments', title: 'svelte/attachments', d: 'svelte-attachments', status: 'reference', seed: 'level-5-profesional/04-reference-modules', pg: true,
		  cover: 'Tipe Attachment; createAttachmentKey; fromAction (adaptasi action lama ke attachment); pemakaian {@attach}.' },
		{ page: 'svelte-compiler', title: 'svelte/compiler', d: 'svelte-compiler', status: 'reference', seed: 'level-5-profesional/04-reference-modules',
		  cover: 'compile, compileModule, parse, preprocess, migrate, VERSION; opsi compiler; bentuk hasil (js/css/warnings).' },
		{ page: 'svelte-easing', title: 'svelte/easing', d: 'svelte-easing', status: 'reference', seed: 'level-5-profesional/04-reference-modules', pg: true,
		  cover: 'Daftar fungsi easing (linear, cubicInOut, elasticOut, dst); tabel + kurva; dipakai di transition/motion/animate.' },
		{ page: 'svelte-events', title: 'svelte/events', d: 'svelte-events', status: 'reference', seed: 'level-5-profesional/04-reference-modules', pg: true,
		  cover: 'on(target, type, handler, opts) untuk attach listener terprogram (mengembalikan cleanup); vs onclick di markup.' },
		{ page: 'svelte-legacy', title: 'svelte/legacy', d: 'svelte-legacy', status: 'reference', seed: 'level-5-profesional/05-migration',
		  cover: 'createBubbler, handlers, nonpassive, once, passive, preventDefault, run, stopPropagation, asClassComponent — bantu migrasi.' },
		{ page: 'svelte-motion', title: 'svelte/motion', d: 'svelte-motion', status: 'reference', seed: 'level-5-profesional/04-reference-modules', pg: true,
		  cover: 'Kelas baru Spring & Tween (new Spring(value, opts), .set/.target/.current); fungsi lama spring()/tweened (legacy); prefersReducedMotion.' },
		{ page: 'svelte-reactivity-window', title: 'svelte/reactivity/window', d: 'svelte-reactivity-window', status: 'reference', seed: 'level-5-profesional/04-reference-modules',
		  cover: 'Reactive wrappers untuk window: innerWidth/innerHeight/scrollX/scrollY/online/devicePixelRatio sebagai nilai reaktif.' },
		{ page: 'svelte-reactivity', title: 'svelte/reactivity', d: 'svelte-reactivity', status: 'reference', seed: 'level-5-profesional/04-reference-modules', pg: true,
		  cover: 'SvelteMap, SvelteSet, SvelteDate, SvelteURL, SvelteURLSearchParams, MediaQuery, createSubscriber — struktur reaktif.' },
		{ page: 'svelte-server', title: 'svelte/server', d: 'svelte-server', status: 'reference', seed: 'level-5-profesional/04-reference-modules',
		  cover: 'render(Component, { props }) untuk SSR (mengembalikan { head, body }); pemakaian di lingkungan server.' },
		{ page: 'svelte-store', title: 'svelte/store', d: 'svelte-store', status: 'reference', seed: 'level-4-special-runtime/02-stores-vs-runes', pg: true,
		  cover: 'writable, readable, derived, readonly, get, toStore, fromStore — API store lengkap + tipe (Writable/Readable).' },
		{ page: 'svelte-transition', title: 'svelte/transition', d: 'svelte-transition', status: 'reference', seed: 'level-3-template/05-transitions', pg: true,
		  cover: 'fade, blur, fly, slide, scale, draw, crossfade — parameter masing-masing + tabel; contoh.' },
		{ page: 'compiler-errors', title: 'Compiler errors', d: 'compiler-errors', status: 'reference', seed: 'level-5-profesional/05-migration',
		  cover: 'Tabel kode error compiler → arti → penyebab umum → cara perbaiki (ambil daftar dari docs/llms.txt).' },
		{ page: 'compiler-warnings', title: 'Compiler warnings', d: 'compiler-warnings', status: 'reference', seed: 'level-5-profesional/05-migration',
		  cover: 'Tabel kode warning compiler → arti → penyebab → perbaikan / cara menonaktifkan (svelte-ignore).' },
		{ page: 'runtime-errors', title: 'Runtime errors', d: 'runtime-errors', status: 'reference', seed: 'level-5-profesional/05-migration',
		  cover: 'Tabel error runtime klien/server → arti → penyebab → perbaikan.' },
		{ page: 'runtime-warnings', title: 'Runtime warnings', d: 'runtime-warnings', status: 'reference', seed: 'level-5-profesional/05-migration',
		  cover: 'Tabel warning runtime (hydration mismatch, ownership, dll) → arti → penyebab → perbaikan.' }
	]),
	...sec('svelte', 'legacy', 'Legacy APIs', 9, [
		{ page: 'overview', title: 'Overview (legacy)', d: 'legacy-overview', status: 'legacy', seed: 'level-5-profesional/05-migration',
		  cover: 'Ringkasan API Svelte 4 (non-runes) yang masih jalan; kapan kamu menemuinya; cara membaca kode lama. Tandai legacy.' },
		{ page: 'let', title: 'Reactive let/var declarations', d: 'legacy-let', status: 'legacy', seed: 'level-5-profesional/05-migration',
		  cover: 'Reaktivitas implisit Svelte 4 (top-level let otomatis reaktif); padanan modern: $state. Tandai legacy.' },
		{ page: 'reactive-assignments', title: 'Reactive $: statements', d: 'legacy-reactive-assignments', status: 'legacy', seed: 'level-5-profesional/05-migration',
		  cover: '$: derivasi & efek; jebakannya; padanan modern $derived/$effect (pakai <LegacyVsModern>).' },
		{ page: 'export-let', title: 'export let', d: 'legacy-export-let', status: 'legacy', seed: 'level-5-profesional/05-migration',
		  cover: 'export let untuk props (Svelte 4); padanan $props(); default & rename. Tandai legacy.' },
		{ page: 'props-and-restprops', title: '$$props and $$restProps', d: 'legacy-$$props-and-$$restProps', status: 'legacy', seed: 'level-5-profesional/05-migration',
		  cover: '$$props/$$restProps lama; padanan ...rest = $props(). Tandai legacy.' },
		{ page: 'on', title: 'on: (legacy events)', d: 'legacy-on', status: 'legacy', seed: 'level-5-profesional/05-migration',
		  cover: 'on:click + modifiers (|preventDefault dll); forwarding; padanan onclick + svelte/legacy helpers. Tandai legacy.' },
		{ page: 'slots', title: '<slot> (legacy)', d: 'legacy-slots', status: 'legacy', seed: 'level-3-template/02-snippets',
		  cover: '<slot>, named slots, slot props (let:); padanan {#snippet}/{@render}. Tandai legacy.' },
		{ page: 'dollar-slots', title: '$$slots', d: 'legacy-$$slots', status: 'legacy', seed: 'level-3-template/02-snippets',
		  cover: '$$slots untuk mengecek slot yang terisi; padanan: cek prop snippet (children). Tandai legacy.' },
		{ page: 'svelte-fragment', title: '<svelte:fragment>', d: 'legacy-svelte-fragment', status: 'legacy', seed: 'level-3-template/02-snippets',
		  cover: '<svelte:fragment slot=…> tanpa wrapper DOM; tidak perlu lagi dengan snippets. Tandai legacy.' },
		{ page: 'svelte-component', title: '<svelte:component>', d: 'legacy-svelte-component', status: 'legacy', seed: 'level-5-profesional/05-migration',
		  cover: '<svelte:component this={Comp}> untuk komponen dinamis (Svelte 4); di Svelte 5 komponen sudah dinamis (render <Comp/> langsung). Tandai legacy.' },
		{ page: 'svelte-self', title: '<svelte:self>', d: 'legacy-svelte-self', status: 'legacy', seed: 'level-5-profesional/05-migration',
		  cover: '<svelte:self> untuk rekursi (Svelte 4); padanan: impor komponen sendiri lewat nama file. Tandai legacy.' },
		{ page: 'component-api', title: 'Imperative component API (legacy)', d: 'legacy-component-api', status: 'legacy', seed: 'level-4-special-runtime/03-context-lifecycle',
		  cover: 'new Component({ target, props }), $set/$on/$destroy (Svelte 4); padanan mount/unmount Svelte 5. Tandai legacy.' }
	])
];

// =====================================================================
// SVELTEKIT (71)
// =====================================================================
const KIT = [
	...sec('kit', 'getting-started', 'Getting started', 1, [
		{ page: 'introduction', title: 'Introduction', d: 'introduction', seed: 'level-6-sveltekit-dasar/01-apa-itu-sveltekit',
		  compare: cmp('Framework vs meta-framework', ['next', 'nuxt'], 'Next.js untuk React, Nuxt untuk Vue, SvelteKit untuk Svelte — peran setara di atas Vite.'),
		  cover: 'SvelteKit = meta-framework full-stack di atas Svelte+Vite; routing/SSR/build; kapan butuh Kit vs Svelte saja.' },
		{ page: 'creating-a-project', title: 'Creating a project', d: 'creating-a-project', seed: 'level-6-sveltekit-dasar/01-apa-itu-sveltekit',
		  cover: 'npx sv create; struktur awal; npm run dev; editor; menambah dependensi; deploy singkat.' },
		{ page: 'project-types', title: 'Project types', d: 'project-types', seed: 'level-6-sveltekit-dasar/01-apa-itu-sveltekit',
		  cover: 'Tipe aplikasi: SSR, SSG/prerender, SPA, library; mana cocok untuk kebutuhan apa.' },
		{ page: 'project-structure', title: 'Project structure', d: 'project-structure', seed: 'level-6-sveltekit-dasar/01-apa-itu-sveltekit',
		  cover: 'src/routes, src/lib, src/app.html, static/, hooks, params; svelte.config.js; file penting & perannya.' },
		{ page: 'web-standards', title: 'Web standards', d: 'web-standards', seed: 'level-6-sveltekit-dasar/02-web-standards',
		  cover: 'Request/Response, Headers, URL, FormData, fetch, streams — API web standar; mengapa bikin portable.' }
	]),
	...sec('kit', 'core', 'Core concepts', 2, [
		{ page: 'routing', title: 'Routing', d: 'routing', seed: 'level-6-sveltekit-dasar/03-routing',
		  compare: cmp('Definisi rute & API endpoint', ['next', 'nuxt'], 'Next App Router (page.tsx/route.ts); Nuxt pages/; SvelteKit +page/+layout/+server. +server = endpoint (mirip Next route handlers / pengganti controller Express/Nest sederhana).'),
		  cover: 'File-based routing; +page(.svelte/.js/.server.js); +layout; +server.js (GET/POST…, json()); +error; params; struktur folder.' },
		{ page: 'load', title: 'Loading data', d: 'load', seed: 'level-6-sveltekit-dasar/04-loading-data',
		  compare: cmp('Mengambil data halaman', ['next', 'nuxt'], 'Next Server Components/getServerSideProps; Nuxt useFetch/useAsyncData; SvelteKit load (universal vs server).'),
		  cover: 'universal (+page.js) vs server (+page.server.js) load; data ke page via $props; layout load; parent(); depends/invalidate; streaming promises.' },
		{ page: 'form-actions', title: 'Form actions', d: 'form-actions', seed: 'level-6-sveltekit-dasar/05-form-actions',
		  analogy: 'formulir kertas yang tetap bisa dikirim via pos walau internet mati, tapi instan kalau ada internet (progressive enhancement).',
		  compare: cmp('Mutasi data dari form', ['next'], 'Next.js Server Actions; SvelteKit form actions bekerja tanpa JS lalu di-enhance dengan use:enhance.'),
		  cover: 'export const actions; default & named actions; use:enhance; fail()/validasi; ActionData; redirect setelah sukses.' },
		{ page: 'page-options', title: 'Page options', d: 'page-options', seed: 'level-6-sveltekit-dasar/06-page-options',
		  analogy: 'restoran: masak lalu antar (SSR), katering disiapkan jauh hari (SSG), kirim bahan mentah biar pelanggan masak (CSR).',
		  compare: cmp('Mode rendering', ['next', 'nuxt'], 'Next/Nuxt punya SSR/SSG/ISR; SvelteKit SSR+prerender (+ISR via adapter/cache header).'),
		  cover: 'export const ssr/csr/prerender/trailingSlash/config/entries; per-route & per-layout; kapan SSR vs SSG vs SPA.' },
		{ page: 'state-management', title: 'State management', d: 'state-management', seed: 'level-6-sveltekit-dasar/07-state-remote',
		  cover: 'Bahaya shared state di server; state aman (context, page data, URL); hindari side-effect di module top-level; store per-request.' },
		{ page: 'remote-functions', title: 'Remote functions', d: 'remote-functions', seed: 'level-6-sveltekit-dasar/07-state-remote',
		  cover: 'query/form/command/prerender (.remote.js) type-safe RPC antara klien & server; kapan dibanding load/actions; status fitur.' },
		{ page: 'environment-variables', title: 'Environment variables', d: 'environment-variables', seed: 'level-8-expert/02-env-vars',
		  cover: 'Konsep env di SvelteKit; static vs dynamic; public (PUBLIC_) vs private; explicit environment variables (2.62+); keamanan agar private tak bocor ke klien.' }
	]),
	...sec('kit', 'build-deploy', 'Build and deploy', 3, [
		{ page: 'building-your-app', title: 'Building your app', d: 'building-your-app', seed: 'level-8-expert/01-building-adapters',
		  cover: 'Tahap build (vite build): analisis, prerender, adapter; $app/environment building; menjalankan hasil build.' },
		{ page: 'adapters', title: 'Adapters', d: 'adapters', seed: 'level-8-expert/01-building-adapters',
		  analogy: 'adapter = colokan listrik universal: aplikasi sama, "steker" menyesuaikan target deploy.',
		  compare: cmp('Deployment target', ['next', 'nuxt'], 'Next Vercel-native; Nuxt presets (nitro); SvelteKit memilih adapter sesuai target.'),
		  cover: 'Apa itu adapter; svelte.config.js adapter; memilih adapter; community adapters.' },
		{ page: 'adapter-auto', title: 'Zero-config deployments', d: 'adapter-auto', seed: 'level-8-expert/01-building-adapters',
		  cover: '@sveltejs/adapter-auto: deteksi platform (Vercel/Netlify/Cloudflare/…); kapan ganti ke adapter spesifik.' },
		{ page: 'adapter-node', title: 'Node servers', d: 'adapter-node', seed: 'level-8-expert/01-building-adapters',
		  cover: 'adapter-node: build server Node; env (PORT/HOST/ORIGIN); menjalankan; reverse proxy; custom server.' },
		{ page: 'adapter-static', title: 'Static site generation', d: 'adapter-static', seed: 'level-8-expert/01-building-adapters',
		  cover: 'adapter-static (SSG): prerender semua; fallback untuk SPA; syarat (no server load dinamis); GitHub Pages.' },
		{ page: 'single-page-apps', title: 'Single-page apps', d: 'single-page-apps', seed: 'level-8-expert/01-building-adapters',
		  cover: 'Mode SPA: ssr=false + fallback adapter-static; trade-off SEO/performa; kapan dipakai.' },
		{ page: 'adapter-cloudflare', title: 'Cloudflare', d: 'adapter-cloudflare', seed: 'level-8-expert/01-building-adapters',
		  cover: 'adapter-cloudflare (Pages/Workers); platform.env bindings (KV/R2/D1); wrangler; batasan runtime.' },
		{ page: 'adapter-cloudflare-workers', title: 'Cloudflare Workers', d: 'adapter-cloudflare-workers', seed: 'level-8-expert/01-building-adapters',
		  cover: 'adapter-cloudflare-workers (Workers-only); konfigurasi wrangler.jsonc; perbedaan dengan adapter-cloudflare.' },
		{ page: 'adapter-netlify', title: 'Netlify', d: 'adapter-netlify', seed: 'level-8-expert/01-building-adapters',
		  cover: 'adapter-netlify; Netlify Functions/Edge; netlify.toml; redirects; batasan.' },
		{ page: 'adapter-vercel', title: 'Vercel', d: 'adapter-vercel', seed: 'level-8-expert/01-building-adapters',
		  cover: 'adapter-vercel; serverless vs edge functions; ISR; image optimization; konfigurasi per-route.' },
		{ page: 'writing-adapters', title: 'Writing adapters', d: 'writing-adapters', seed: 'level-8-expert/01-building-adapters',
		  cover: 'Membuat adapter sendiri: Adapter API (adapt, emulate, supports); builder helpers; kapan perlu.' }
	]),
	...sec('kit', 'advanced', 'Advanced', 4, [
		{ page: 'advanced-routing', title: 'Advanced routing', d: 'advanced-routing', seed: 'level-7-sveltekit-lanjutan/01-advanced-routing',
		  cover: '[...rest], [[optional]], param matchers (src/params), route groups (group), layout breaking (+page@), encoding, sorting.' },
		{ page: 'hooks', title: 'Hooks', d: 'hooks', seed: 'level-7-sveltekit-lanjutan/02-hooks',
		  analogy: 'hooks = satpam di pintu masuk: tiap request lewat sini sebelum sampai ke route.',
		  cover: 'hooks.server.js: handle (event+resolve), handleFetch, handleValidationError, locals; hooks.js: reroute, transport; handleError; sequence().' },
		{ page: 'errors', title: 'Errors', d: 'errors', seed: 'level-7-sveltekit-lanjutan/03-errors-links-sw',
		  cover: 'Expected (error()) vs unexpected errors; +error.svelte; $page.error; handleError; status & message; type App.Error.' },
		{ page: 'link-options', title: 'Link options', d: 'link-options', seed: 'level-7-sveltekit-lanjutan/03-errors-links-sw',
		  cover: 'data-sveltekit-preload-data/preload-code/reload/replacestate/keepfocus/noscroll; mengatur prefetch & navigasi.' },
		{ page: 'service-workers', title: 'Service workers', d: 'service-workers', seed: 'level-7-sveltekit-lanjutan/03-errors-links-sw',
		  analogy: 'service worker = pelayan yang mengingat pesananmu (cache) supaya app tetap jalan saat offline.',
		  cover: 'src/service-worker.js; $service-worker (build/files/version); strategi cache; offline; registrasi otomatis.' },
		{ page: 'server-only-modules', title: 'Server-only modules', d: 'server-only-modules', seed: 'level-7-sveltekit-lanjutan/04-server-only-advanced',
		  cover: '$lib/server, *.server.js, $env/static/private — mencegah kode/rahasia server bocor ke klien; cara kerja guard.' },
		{ page: 'snapshots', title: 'Snapshots', d: 'snapshots', seed: 'level-7-sveltekit-lanjutan/04-server-only-advanced',
		  cover: 'export const snapshot = { capture, restore } untuk menyimpan state UI ephemeral saat navigasi; batasan ukuran.' },
		{ page: 'shallow-routing', title: 'Shallow routing', d: 'shallow-routing', seed: 'level-7-sveltekit-lanjutan/04-server-only-advanced',
		  cover: 'pushState/replaceState dari $app/navigation; preloadData; modal berbasis history; page.state.' },
		{ page: 'observability', title: 'Observability', d: 'observability', seed: 'level-7-sveltekit-lanjutan/04-server-only-advanced',
		  cover: 'Tracing (OpenTelemetry), instrumentation.server.js, span; memantau load/actions; konfigurasi.' },
		{ page: 'packaging', title: 'Packaging', d: 'packaging', seed: 'level-7-sveltekit-lanjutan/04-server-only-advanced',
		  cover: '@sveltejs/package (svelte-package): membangun library Svelte; exports map; svelte field; publish ke npm.' }
	]),
	...sec('kit', 'best-practices', 'Best practices', 5, [
		{ page: 'auth', title: 'Auth', d: 'auth', seed: 'level-8-expert/05-auth-perf-seo',
		  cover: 'Session vs token; cookies; hooks + locals; melindungi route (load/hooks); pola login/logout; library (Lucia/Auth.js).' },
		{ page: 'performance', title: 'Performance', d: 'performance', seed: 'level-8-expert/05-auth-perf-seo',
		  cover: 'Mengukur (Lighthouse); preload; code-split; menghindari waterfalls (parallel load); caching; font/asset.' },
		{ page: 'icons', title: 'Icons', d: 'icons', seed: 'level-8-expert/05-auth-perf-seo',
		  cover: 'Strategi icon (SVG inline, sprite, library seperti unplugin-icons); trade-off ukuran & a11y.' },
		{ page: 'images', title: 'Images', d: 'images', seed: 'level-8-expert/05-auth-perf-seo',
		  cover: '@sveltejs/enhanced-img; Vite asset; lazy loading; ukuran responsif & format modern; CDN gambar.' },
		{ page: 'accessibility', title: 'Accessibility', d: 'accessibility', seed: 'level-8-expert/05-auth-perf-seo',
		  cover: 'Pengumuman route (live region), fokus, lang, peringatan a11y compiler; praktik ARIA; testing.' },
		{ page: 'seo', title: 'SEO', d: 'seo', seed: 'level-8-expert/05-auth-perf-seo',
		  cover: 'SSR untuk crawler; <svelte:head> title/meta; sitemap & robots; canonical; performance sebagai faktor SEO.' }
	]),
	...sec('kit', 'appendix', 'Appendix', 6, [
		{ page: 'faq', title: 'Frequently asked questions', d: 'faq', seed: 'level-6-sveltekit-dasar/01-apa-itu-sveltekit',
		  cover: 'FAQ SvelteKit: pakai library X, HMR, alias, deployment, env, dsb. Tabel tanya-jawab ringkas.' },
		{ page: 'integrations', title: 'Integrations', d: 'integrations', seed: 'level-8-expert/05-auth-perf-seo',
		  cover: 'vitePreprocess; menambah integrasi (Tailwind, MDsveX, dll) lewat sv add; database/ORM; testing.' },
		{ page: 'debugging', title: 'Breakpoint Debugging', d: 'debugging', seed: 'level-7-sveltekit-lanjutan/02-hooks',
		  cover: 'Debug dengan breakpoint (VS Code launch.json, --inspect); debug server vs klien; source maps.' },
		{ page: 'migrating-to-sveltekit-2', title: 'Migrating to SvelteKit v2', d: 'migrating-to-sveltekit-2', seed: 'level-8-expert/01-building-adapters',
		  cover: 'Perubahan v1→v2: error()/redirect() tanpa throw; cookies path; top-level promises; Node 18+; tabel breaking changes.' },
		{ page: 'migrating', title: 'Migrating from Sapper', d: 'migrating', seed: 'level-8-expert/01-building-adapters',
		  cover: 'Migrasi Sapper → SvelteKit: struktur route, preload→load, sapper API→$app, regreso; ringkas (historis).' },
		{ page: 'additional-resources', title: 'Additional resources', d: 'additional-resources', seed: 'level-8-expert/06-studi-kasus',
		  cover: 'Tutorial resmi, contoh, komunitas (Discord), integrasi, FAQ — kumpulan tautan belajar lanjutan.' },
		{ page: 'glossary', title: 'Glossary', d: 'glossary', seed: 'level-6-sveltekit-dasar/06-page-options',
		  cover: 'Istilah: CSR, SSR, SSG, prerender, hydration, SPA, edge, routing — definisi singkat + relevansi.' }
	]),
	...sec('kit', 'reference', 'Reference', 7, [
		{ page: 'sveltejs-kit', title: '@sveltejs/kit', d: '@sveltejs-kit', status: 'reference', seed: 'level-8-expert/04-api-routes',
		  cover: 'Export inti: error, redirect, json, text, fail, isHttpError, isRedirect, isActionFailure; tipe (RequestHandler, Load, Actions, Handle, Cookies, RequestEvent, Config...).' },
		{ page: 'sveltejs-kit-hooks', title: '@sveltejs/kit/hooks', d: '@sveltejs-kit-hooks', status: 'reference', seed: 'level-7-sveltekit-lanjutan/02-hooks',
		  cover: 'sequence(...handlers) untuk menggabungkan beberapa handle; urutan resolve; transformPageChunk.' },
		{ page: 'sveltejs-kit-node-polyfills', title: '@sveltejs/kit/node/polyfills', d: '@sveltejs-kit-node-polyfills', status: 'reference', seed: 'level-8-expert/01-building-adapters',
		  cover: 'installPolyfills() menambah Web API global (fetch/Headers/Request/Response) di Node lama; dipakai adapter.' },
		{ page: 'sveltejs-kit-node', title: '@sveltejs/kit/node', d: '@sveltejs-kit-node', status: 'reference', seed: 'level-8-expert/01-building-adapters',
		  cover: 'getRequest/setResponse: jembatan antara IncomingMessage/ServerResponse Node dan Request/Response web; dipakai adapter Node.' },
		{ page: 'sveltejs-kit-vite', title: '@sveltejs/kit/vite', d: '@sveltejs-kit-vite', status: 'reference', seed: 'level-8-expert/01-building-adapters',
		  cover: 'sveltekit() plugin Vite; integrasi build/dev; konfigurasi vite.config.js.' },
		{ page: 'app-environment', title: '$app/environment', d: '$app-environment', status: 'reference', seed: 'level-8-expert/03-app-modules',
		  cover: 'browser, building, dev, version — konstanta lingkungan; kapan masing-masing true; pemakaian.' },
		{ page: 'app-forms', title: '$app/forms', d: '$app-forms', status: 'reference', seed: 'level-8-expert/03-app-modules',
		  cover: 'enhance(form, submit), applyAction, deserialize — progressive enhancement form actions; callback ActionResult.' },
		{ page: 'app-navigation', title: '$app/navigation', d: '$app-navigation', status: 'reference', seed: 'level-8-expert/03-app-modules',
		  cover: 'goto, invalidate, invalidateAll, preloadData, preloadCode, beforeNavigate, afterNavigate, onNavigate, pushState, replaceState, disableScrollHandling.' },
		{ page: 'app-paths', title: '$app/paths', d: '$app-paths', status: 'reference', seed: 'level-8-expert/03-app-modules',
		  cover: 'base, assets, resolveRoute/resolve — path-aware URL; konfigurasi paths.base; pemakaian di link.' },
		{ page: 'app-server', title: '$app/server', d: '$app-server', status: 'reference', seed: 'level-8-expert/03-app-modules',
		  cover: 'getRequestEvent, read, command/form/query/prerender (remote) — API khusus server; akses request di luar handler.' },
		{ page: 'app-state', title: '$app/state', d: '$app-state', status: 'reference', seed: 'level-8-expert/03-app-modules',
		  cover: 'page, navigating, updated (rune-based, pengganti $app/stores); akses reaktif tanpa $; perbedaan dari stores.' },
		{ page: 'app-stores', title: '$app/stores', d: '$app-stores', status: 'reference', seed: 'level-8-expert/03-app-modules',
		  cover: 'page, navigating, updated, getStores (store lama, dipakai dengan $); deprecated demi $app/state; kapan masih relevan.' },
		{ page: 'app-types', title: '$app/types', d: '$app-types', status: 'reference', seed: 'level-8-expert/03-app-modules',
		  cover: 'Tipe yang dihasilkan: RouteId, RouteParams, LayoutParams, Pathname, ResolvedPathname, Asset; pemakaian type-safe.' },
		{ page: 'env-dynamic-private', title: '$env/dynamic/private', d: '$env-dynamic-private', status: 'reference', seed: 'level-8-expert/02-env-vars',
		  cover: 'env runtime privat (process.env saat jalan); hanya server; beda dari static; kapan dipakai.' },
		{ page: 'env-dynamic-public', title: '$env/dynamic/public', d: '$env-dynamic-public', status: 'reference', seed: 'level-8-expert/02-env-vars',
		  cover: 'env runtime publik (prefix PUBLIC_); bisa di klien; dibaca saat runtime.' },
		{ page: 'env-static-private', title: '$env/static/private', d: '$env-static-private', status: 'reference', seed: 'level-8-expert/02-env-vars',
		  cover: 'env privat yang di-inline saat build (tree-shakeable); hanya server; .env; keamanan.' },
		{ page: 'env-static-public', title: '$env/static/public', d: '$env-static-public', status: 'reference', seed: 'level-8-expert/02-env-vars',
		  cover: 'env publik (PUBLIC_) di-inline saat build; aman di klien; perbedaan dari dynamic.' },
		{ page: 'app-env', title: '$app/env', d: '$app-env', status: 'reference', seed: 'level-8-expert/02-env-vars',
		  cover: 'Alias $app/env (saat explicit env aktif, 2.62+): browser/building/dev/version; hubungan dengan $app/environment.' },
		{ page: 'app-env-private', title: '$app/env/private', d: '$app-env-private', status: 'reference', seed: 'level-8-expert/02-env-vars',
		  cover: 'Explicit environment variables privat (2.62+): mendeklarasikan & mengakses env privat secara type-safe.' },
		{ page: 'app-env-public', title: '$app/env/public', d: '$app-env-public', status: 'reference', seed: 'level-8-expert/02-env-vars',
		  cover: 'Explicit environment variables publik (2.62+): env publik type-safe yang aman di klien.' },
		{ page: 'lib', title: '$lib', d: '$lib', status: 'reference', seed: 'level-6-sveltekit-dasar/01-apa-itu-sveltekit',
		  cover: 'Alias $lib → src/lib; $lib/server; konfigurasi files.lib; impor bersih.' },
		{ page: 'service-worker', title: '$service-worker', d: '$service-worker', status: 'reference', seed: 'level-7-sveltekit-lanjutan/03-errors-links-sw',
		  cover: 'build, files, prerendered, version, base — variabel di dalam service worker; membangun cache list.' },
		{ page: 'configuration', title: 'Configuration', d: 'configuration', status: 'reference', seed: 'level-8-expert/01-building-adapters',
		  cover: 'svelte.config.js kit options: adapter, alias, csp, csrf, env, files, paths, prerender, version, serviceWorker, dll — tabel lengkap.' },
		{ page: 'cli', title: 'Command Line Interface', d: 'cli', status: 'reference', seed: 'level-6-sveltekit-dasar/01-apa-itu-sveltekit',
		  cover: 'vite dev/build/preview; svelte-kit sync; flag; perbedaan dari CLI sv.' },
		{ page: 'types', title: 'Types', d: 'types', status: 'reference', seed: 'level-8-expert/03-app-modules',
		  cover: 'App namespace (Error, Locals, PageData, PageState, Platform); $types generated (PageLoad/PageServerLoad/Actions); Generated types.' }
	])
];

// =====================================================================
// CLI — sv (21)
// =====================================================================
const CLI = [
	...sec('cli', 'intro', 'Pengantar', 1, [
		{ page: 'overview', title: 'Overview', d: 'overview', seed: 'level-1-dasar/02-setup-tooling',
		  cover: 'Apa itu sv (Svelte CLI); npx sv; perintah utama (create/add/check/migrate); add-ons; instalasi.' },
		{ page: 'faq', title: 'Frequently asked questions', d: 'faq', seed: 'level-1-dasar/02-setup-tooling',
		  cover: 'FAQ sv: package manager, perbedaan sv vs create-svelte lama, add-ons, troubleshooting.' }
	]),
	...sec('cli', 'commands', 'Perintah', 2, [
		{ page: 'sv-create', title: 'sv create', d: 'sv-create', seed: 'level-1-dasar/02-setup-tooling',
		  cover: 'npx sv create: memilih template, opsi (TS/ESLint/Prettier/Playwright/Vitest), add-ons; flag; struktur hasil.' },
		{ page: 'sv-add', title: 'sv add', d: 'sv-add', seed: 'level-1-dasar/02-setup-tooling',
		  cover: 'sv add <addon>: menambahkan integrasi ke proyek ada (tailwind, drizzle, dll); flag; cara kerja patch.' },
		{ page: 'sv-check', title: 'sv check', d: 'sv-check', seed: 'level-5-profesional/02-testing',
		  cover: 'sv check: diagnostik tipe & Svelte (svelte-check) ; opsi (--watch, --threshold); CI.' },
		{ page: 'sv-migrate', title: 'sv migrate', d: 'sv-migrate', seed: 'level-5-profesional/05-migration',
		  cover: 'sv migrate <target> (svelte-5, sveltekit-2, self-closing-tags, dll); apa yang diubah otomatis; tinjau hasil.' }
	]),
	...sec('cli', 'addons', 'Add-ons', 3, [
		{ page: 'better-auth', title: 'better-auth', d: 'better-auth', seed: 'level-8-expert/05-auth-perf-seo',
		  cover: 'Add-on better-auth: setup autentikasi; file yang ditambahkan; konfigurasi; langkah lanjutan.' },
		{ page: 'drizzle', title: 'drizzle', d: 'drizzle', seed: 'level-8-expert/04-api-routes',
		  cover: 'Add-on drizzle (ORM): memilih database (SQLite/Postgres/MySQL); schema; koneksi; migrasi.' },
		{ page: 'eslint', title: 'eslint', d: 'eslint', seed: 'level-5-profesional/01-best-practices-ts',
		  cover: 'Add-on eslint: konfigurasi lint untuk Svelte/TS; integrasi prettier; script.' },
		{ page: 'mcp', title: 'mcp', d: 'mcp', seed: 'level-1-dasar/02-setup-tooling',
		  cover: 'Add-on mcp: server Model Context Protocol untuk proyek Svelte; kegunaan dengan AI tooling.' },
		{ page: 'mdsvex', title: 'mdsvex', d: 'mdsvex', seed: 'level-1-dasar/02-setup-tooling',
		  cover: 'Add-on mdsvex: menulis Markdown + komponen Svelte (.svx); konfigurasi; layout.' },
		{ page: 'paraglide', title: 'paraglide', d: 'paraglide', seed: 'level-8-expert/05-auth-perf-seo',
		  cover: 'Add-on paraglide (i18n): pesan terjemahan type-safe; routing locale; setup.' },
		{ page: 'playwright', title: 'playwright', d: 'playwright', seed: 'level-5-profesional/02-testing',
		  cover: 'Add-on playwright: E2E testing; struktur tes; menjalankan; CI.' },
		{ page: 'prettier', title: 'prettier', d: 'prettier', seed: 'level-5-profesional/01-best-practices-ts',
		  cover: 'Add-on prettier: format kode + plugin Svelte; integrasi eslint; script format.' },
		{ page: 'storybook', title: 'storybook', d: 'storybook', seed: 'level-5-profesional/02-testing',
		  cover: 'Add-on storybook: katalog komponen; stories untuk komponen Svelte; menjalankan.' },
		{ page: 'sveltekit-adapter', title: 'sveltekit-adapter', d: 'sveltekit-adapter', seed: 'level-8-expert/01-building-adapters',
		  cover: 'Add-on sveltekit-adapter: memilih & memasang adapter deploy (node/static/cloudflare/vercel/netlify/auto).' },
		{ page: 'tailwind', title: 'tailwindcss', d: 'tailwind', seed: 'level-1-dasar/05-styling',
		  cover: 'Add-on tailwindcss: setup Tailwind v4 di SvelteKit; konfigurasi; plugin; pemakaian kelas.' },
		{ page: 'vitest', title: 'vitest', d: 'vitest', seed: 'level-5-profesional/02-testing',
		  cover: 'Add-on vitest: unit testing; konfigurasi browser/jsdom; testing komponen & .svelte.ts.' },
		{ page: 'community', title: 'Create your own add-on', d: 'community', seed: 'level-1-dasar/02-setup-tooling',
		  cover: 'Membuat community add-on: struktur, API add-on (sv), publish, mendaftarkan; menjalankan add-on pihak ketiga.' }
	]),
	...sec('cli', 'api', 'API', 4, [
		{ page: 'sv', title: 'sv', d: 'sv', status: 'reference', seed: 'level-1-dasar/02-setup-tooling',
		  cover: 'API @sveltejs/cli untuk membuat add-on terprogram: defineAddon, workspace, prompts, file ops; tipe.' },
		{ page: 'sv-utils', title: 'sv-utils', d: 'sv-utils', status: 'reference', seed: 'level-1-dasar/02-setup-tooling',
		  cover: '@sveltejs/sv-utils (eksperimental): transforms AST (js/svelte/css/json/yaml/toml), parser, package-manager helpers.' }
	])
];

export const PAGES = [...SVELTE, ...KIT, ...CLI];
